---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: fio-job-config
data:
  # https://s905060.gitbooks.io/site-reliability-engineer-handbook/content/fio.html
  # 8K block, 16 jobs
  fio.job: |-
    [global]
    ioengine=libaio
    iodepth=128
    rw=randrw
    bs=8K
    direct=1
    size=1G
    numjobs=12
    ramp_time=5
    runtime=60
    time_based
    group_reporting
    [testjob]
