---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio
  labels:
    app: fio
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      labels:
        app: fio
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fio
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: fio
        image: joshuarobinson/fio:3.19
        command: ["sh"]
        args: ["-c", "echo ${HOSTNAME} && mkdir -p /scratch/${HOSTNAME} && fio /configs/fio.job --eta=never --directory=/scratch/${HOSTNAME}"]
        volumeMounts:
        - name: fio-config-vol
          mountPath: /configs
        - name: fio-data
          mountPath: /scratch
        imagePullPolicy: Always
      restartPolicy: Never
      volumes:
      - name: fio-config-vol
        configMap:
          name: fio-job-config
      - name: fio-data
        emptyDir: {}
